version: '3.1'

services:

  pg:
    image: postgres:13
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker1234
    ports:
      - '5433:5432'
    privileged: true
    volumes:
      - pg5:/var/lib/postgresql/data

  # redis:
  #   image: redis:alpine
  #   restart: "always"
  #   ports:
  #     - 6379:6379

volumes:
  pg5:
